name: CI
on:
  pull_request:
    branches: [main, master]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          cat .env  # Debugging: Show contents of .env (remove this if it works)

      - name: Turn on 'editable' mode
        run: pipenv install -e . --skip-lock

      - name: Install pytest
        run: pipenv install pytest

      - name: Load environment variables & Run tests
        run: |
          pipenv run python -c "import dotenv; dotenv.load_dotenv()"
          pipenv run pytest